[workspace]
members = [
  "crates/core",
  "crates/clip",
  "crates/engine",
  "crates/audio",
  "crates/surface",
  "crates/session",
  "crates/app",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT"
readme = "README.md"
repository = "https://github.com/henrymbaldwin/free-loop"
keywords = ["looper", "launchpad", "audio", "midi", "dawless"]
categories = ["multimedia::audio"]

[workspace.dependencies]
core-foundation = "0.10"
cpal = "0.18"
ctrlc = "3"
free-loop-audio = { path = "crates/audio", version = "0.1.0" }
free-loop-clip = { path = "crates/clip", version = "0.1.0" }
free-loop-core = { path = "crates/core", version = "0.1.0" }
free-loop-engine = { path = "crates/engine", version = "0.1.0" }
free-loop-session = { path = "crates/session", version = "0.1.0" }
free-loop-surface = { path = "crates/surface", version = "0.1.0" }
hound = "3.5"
launchy = { git = "https://github.com/HenryMBaldwin/launchy", rev = "c88be0f13197e8cf098e99f9e766335488e83329" }
midir = "0.11"
rtrb = "0.3"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
toml = "1"

[workspace.lints.rust]
future_incompatible = { level = "deny", priority = -1 }
missing_debug_implementations = "warn"
# missing_docs = "warn"
nonstandard_style = { level = "deny", priority = -1 }
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
dbg_macro = "warn"
expect_used = "warn"
module_name_repetitions = "allow"
multiple_crate_versions = "allow"
must_use_candidate = "allow"
panic = "warn"
pedantic = { level = "warn", priority = -1 }
todo = "warn"
unimplemented = "warn"
unwrap_used = "warn"
